// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: hedge/v1/debian.proto

package hedge

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DebianPackage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Package       string `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	Source        string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Version       string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	InstalledSize uint64 `protobuf:"varint,4,opt,name=installed_size,json=installedSize,proto3" json:"installed_size,omitempty"`
}

func (x *DebianPackage) Reset() {
	*x = DebianPackage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hedge_v1_debian_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DebianPackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebianPackage) ProtoMessage() {}

func (x *DebianPackage) ProtoReflect() protoreflect.Message {
	mi := &file_hedge_v1_debian_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebianPackage.ProtoReflect.Descriptor instead.
func (*DebianPackage) Descriptor() ([]byte, []int) {
	return file_hedge_v1_debian_proto_rawDescGZIP(), []int{0}
}

func (x *DebianPackage) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *DebianPackage) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *DebianPackage) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DebianPackage) GetInstalledSize() uint64 {
	if x != nil {
		return x.InstalledSize
	}
	return 0
}

type DebianPackages struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Packages []*DebianPackage `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`
}

func (x *DebianPackages) Reset() {
	*x = DebianPackages{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hedge_v1_debian_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DebianPackages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebianPackages) ProtoMessage() {}

func (x *DebianPackages) ProtoReflect() protoreflect.Message {
	mi := &file_hedge_v1_debian_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebianPackages.ProtoReflect.Descriptor instead.
func (*DebianPackages) Descriptor() ([]byte, []int) {
	return file_hedge_v1_debian_proto_rawDescGZIP(), []int{1}
}

func (x *DebianPackages) GetPackages() []*DebianPackage {
	if x != nil {
		return x.Packages
	}
	return nil
}

var File_hedge_v1_debian_proto protoreflect.FileDescriptor

var file_hedge_v1_debian_proto_rawDesc = []byte{
	0x0a, 0x15, 0x68, 0x65, 0x64, 0x67, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x65, 0x62, 0x69, 0x61,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x68, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x76,
	0x31, 0x22, 0x82, 0x01, 0x0a, 0x0d, 0x44, 0x65, 0x62, 0x69, 0x61, 0x6e, 0x50, 0x61, 0x63, 0x6b,
	0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x25, 0x0a, 0x0e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x5f, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c,
	0x65, 0x64, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x45, 0x0a, 0x0e, 0x44, 0x65, 0x62, 0x69, 0x61, 0x6e,
	0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x12, 0x33, 0x0a, 0x08, 0x70, 0x61, 0x63, 0x6b,
	0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x68, 0x65, 0x64,
	0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x62, 0x69, 0x61, 0x6e, 0x50, 0x61, 0x63, 0x6b,
	0x61, 0x67, 0x65, 0x52, 0x08, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x42, 0x79, 0x0a,
	0x0c, 0x63, 0x6f, 0x6d, 0x2e, 0x68, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x42, 0x0b, 0x44,
	0x65, 0x62, 0x69, 0x61, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x1b, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x68, 0x65, 0x70, 0x77, 0x61, 0x67,
	0x6e, 0x65, 0x72, 0x2f, 0x68, 0x65, 0x64, 0x67, 0x65, 0xa2, 0x02, 0x03, 0x48, 0x58, 0x58, 0xaa,
	0x02, 0x08, 0x48, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x08, 0x48, 0x65, 0x64,
	0x67, 0x65, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x14, 0x48, 0x65, 0x64, 0x67, 0x65, 0x5c, 0x56, 0x31,
	0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x09, 0x48,
	0x65, 0x64, 0x67, 0x65, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hedge_v1_debian_proto_rawDescOnce sync.Once
	file_hedge_v1_debian_proto_rawDescData = file_hedge_v1_debian_proto_rawDesc
)

func file_hedge_v1_debian_proto_rawDescGZIP() []byte {
	file_hedge_v1_debian_proto_rawDescOnce.Do(func() {
		file_hedge_v1_debian_proto_rawDescData = protoimpl.X.CompressGZIP(file_hedge_v1_debian_proto_rawDescData)
	})
	return file_hedge_v1_debian_proto_rawDescData
}

var file_hedge_v1_debian_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hedge_v1_debian_proto_goTypes = []interface{}{
	(*DebianPackage)(nil),  // 0: hedge.v1.DebianPackage
	(*DebianPackages)(nil), // 1: hedge.v1.DebianPackages
}
var file_hedge_v1_debian_proto_depIdxs = []int32{
	0, // 0: hedge.v1.DebianPackages.packages:type_name -> hedge.v1.DebianPackage
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_hedge_v1_debian_proto_init() }
func file_hedge_v1_debian_proto_init() {
	if File_hedge_v1_debian_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hedge_v1_debian_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DebianPackage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hedge_v1_debian_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DebianPackages); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hedge_v1_debian_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hedge_v1_debian_proto_goTypes,
		DependencyIndexes: file_hedge_v1_debian_proto_depIdxs,
		MessageInfos:      file_hedge_v1_debian_proto_msgTypes,
	}.Build()
	File_hedge_v1_debian_proto = out.File
	file_hedge_v1_debian_proto_rawDesc = nil
	file_hedge_v1_debian_proto_goTypes = nil
	file_hedge_v1_debian_proto_depIdxs = nil
}
